### ISSUE TITLE
Wywala się przy uruchamianiu maina na rewrite

### ISSUE THREAD

**Issue by er713** [er713/Schooling-RL#43]
Branch: [rewrite](/er713/Schooling-RL/tree/rewrite)

```
Traceback (most recent call last):
  File "/home/student/Schooling-RL/src/main.py", line 64, in <module>
    c.run(timeToExam=timeToExam, numberOfIteration=1000, saveResults=True, visualiseResults=True, savePlot=True)
  File "/home/student/Schooling-RL/src/school/classroom.py", line 195, in run
    result, _ = self._run_single_learning(timeToExam, learningType, examTasks, saveResults, plotter)
  File "/home/student/Schooling-RL/src/school/classroom.py", line 266, in _run_single_learning
    self.learning_process(timeToExam, learningType)
  File "/home/student/Schooling-RL/src/school/classroom.py", line 86, in learning_process
    self._learning_types[learningType](timeToExam)
  File "/home/student/Schooling-RL/src/school/classroom.py", line 102, in _learning_loop_all_student
    self._learn_student(student, last=(time == timeToExam - 1))
  File "/home/student/Schooling-RL/src/school/classroom.py", line 120, in _learn_student
    task = self.teacher.choose_task(student)
  File "/home/student/Schooling-RL/src/school/teachers/teacher_n_last_history_rewrite.py", line 36, in choose_task
    return super().choose_task(student.id)
  File "/home/student/Schooling-RL/src/school/teachers/teacher_rl.py", line 29, in choose_task
    action = self.get_action(state)
  File "/home/student/Schooling-RL/src/school/teachers/dqn_teachers/dqn_table_teacher.py", line 135, in get_action
    action = [task_ for task_ in self.tasks if task_.id == action][0]
IndexError: list index out of range
```

**Comment by er713** [comment]
Zrobione przez @aizemski 
Zmiany na branchu [rewrite](/er713/Schooling-RL/tree/rewrite)
